module.exports = {
  // HTTP Status Codes
  HTTP_STATUS: {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503
  },

  // Error Codes
  ERROR_CODES: {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
    INVALID_REQUEST_FORMAT: 'INVALID_REQUEST_FORMAT',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    INTERNAL_ERROR: 'INTERNAL_ERROR'
  },

  // Transaction Types
  TRANSACTION_TYPES: {
    POLICY_LOOKUP: 'POLICY_LOOKUP',
    PREMIUM_PAYMENT: 'PREMIUM_PAYMENT',
    QUOTE_GENERATION: 'QUOTE_GENERATION',
    CLAIM_SUBMISSION: 'CLAIM_SUBMISSION',
    LICENSE_RENEWAL: 'LICENSE_RENEWAL',
    POLICY_CREATION: 'POLICY_CREATION'
  },

  // Transaction Status
  TRANSACTION_STATUS: {
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    CANCELLED: 'CANCELLED',
    REFUNDED: 'REFUNDED'
  },

  // Policy Status
  POLICY_STATUS: {
    ACTIVE: 'ACTIVE',
    LAPSED: 'LAPSED',
    SUSPENDED: 'SUSPENDED',
    CANCELLED: 'CANCELLED',
    EXPIRED: 'EXPIRED'
  },

  // Insurance Product Types
  INSURANCE_TYPES: {
    MOTOR: 'MOTOR',
    TRAVEL: 'TRAVEL',
    PERSONAL_ACCIDENT: 'PERSONAL_ACCIDENT',
    PET: 'PET',
    LEGAL: 'LEGAL',
    BUSINESS: 'BUSINESS',
    HEALTH: 'HEALTH'
  },

  // Motor Insurance Cover Types
  MOTOR_COVER_TYPES: {
    COMPREHENSIVE: 'COMPREHENSIVE',
    COMPREHENSIVE_ZINARA: 'COMPREHENSIVE_ZINARA',
    COMPREHENSIVE_ZINARA_RADIO: 'COMPREHENSIVE_ZINARA_RADIO',
    THIRD_PARTY: 'THIRD_PARTY',
    THIRD_PARTY_ZINARA: 'THIRD_PARTY_ZINARA',
    THIRD_PARTY_ZINARA_RADIO: 'THIRD_PARTY_ZINARA_RADIO'
  },

  // Rating Types
  RATING_TYPES: {
    FLAT_PREMIUM: 'FLAT_PREMIUM',
    PERCENTAGE: 'PERCENTAGE',
    DURATION_BASED: 'DURATION_BASED'
  },

  // Currencies
  CURRENCIES: {
    USD: 'USD',
    ZWL: 'ZWL',
    ZAR: 'ZAR'
  },

  // Partner Integration Types
  INTEGRATION_TYPES: {
    BANK_INTEGRATION: 'BANK_INTEGRATION',
    INSURANCE_PROVIDER: 'INSURANCE_PROVIDER',
    MOBILE_MONEY: 'MOBILE_MONEY',
    API_GATEWAY: 'API_GATEWAY',
    TEST_PARTNER: 'TEST_PARTNER'
  },

  // Zimnat Specific Constants
  ZIMNAT: {
    API_ENDPOINTS: {
      TPI_QUOTES: '/api/icecash/TPIQuotes',
      TPI_QUOTE_UPDATE: '/api/icecash/TPIQuoteUpdate',
      TPI_POLICY_STATUS: '/api/icecash/TPIPolicyStatus',
      CLAIM_NUMBER: '/api/pure/claimNumber',
      AUTHENTICATE: '/api/authenticate'
    },
    INSURANCE_TYPES: {
      COMPREHENSIVE: 1,
      THIRD_PARTY: 2,
      COMMERCIAL: 3
    },
    CLAIM_STATUS: {
      PENDING: 0,
      APPROVED: 1,
      REJECTED: 2,
      PROCESSING: 3
    }
  },

  // Validation Rules
  VALIDATION: {
    MAX_STRING_LENGTH: 255,
    MAX_TEXT_LENGTH: 1000,
    MAX_DESCRIPTION_LENGTH: 2000,
    MIN_PASSWORD_LENGTH: 8,
    MAX_FILE_SIZE: 10 * 1024 * 1024, // 10MB
    ALLOWED_FILE_TYPES: ['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx']
  },

  // Cache TTL (Time To Live) in seconds
  CACHE_TTL: {
    SHORT: 300, // 5 minutes
    MEDIUM: 1800, // 30 minutes
    LONG: 3600, // 1 hour
    VERY_LONG: 86400 // 24 hours
  },

  // Rate Limiting
  RATE_LIMITS: {
    GENERAL: {
      WINDOW: 15 * 60 * 1000, // 15 minutes
      MAX: 1000
    },
    AUTH: {
      WINDOW: 15 * 60 * 1000, // 15 minutes
      MAX: 20
    },
    ADMIN: {
      WINDOW: 15 * 60 * 1000, // 15 minutes
      MAX: 100
    },
    ZIMNAT: {
      WINDOW: 1 * 60 * 1000, // 1 minute
      MAX: 200
    }
  }
};
