exports.seed = async function(knex) {
  await knex('enum_suburbs_towns').del();

  const suburbsTowns = [
    { suburb_id: 1, town: 'HARARE', suburb: 'ACADIA' },
    { suburb_id: 2, town: 'CHINHOYI', suburb: 'ALASKA' },
    { suburb_id: 3, town: 'HARARE', suburb: 'ALEXANDRA PARK' },
    { suburb_id: 4, town: 'KWEKWE', suburb: 'AMAVENI' },
    { suburb_id: 5, town: 'HARARE', suburb: 'ARDBENIE' },
    { suburb_id: 6, town: 'BULAWAYO', suburb: 'ASCOT' },
    { suburb_id: 7, town: 'GWERU', suburb: 'ASCOT' },
    { suburb_id: 8, town: 'HARARE', suburb: 'ASHDON PARK' },
    { suburb_id: 9, town: 'MVUMA', suburb: 'ATHENS MINE' },
    { suburb_id: 10, town: 'GWERU', suburb: 'ATHLONE' },
    { suburb_id: 11, town: 'BULAWAYO', suburb: 'AVENUES' },
    { suburb_id: 12, town: 'HARARE', suburb: 'AVENUES' },
    { suburb_id: 13, town: 'HARARE', suburb: 'AVONDALE' },
    { suburb_id: 14, town: 'HARARE', suburb: 'AVONLEA' },
    { suburb_id: 15, town: 'HARARE', suburb: 'BALLANTYNE PARK' },
    { suburb_id: 16, town: 'GOKWE', suburb: 'BAMBANANI COMPLEX' },
    { suburb_id: 17, town: 'HWANKE', suburb: 'BAOBAB HILL' },
    { suburb_id: 18, town: 'KARIBA', suburb: 'BAOBAB RIDGE' },
    { suburb_id: 19, town: 'BULAWAYO', suburb: 'BARHAM GREEN' },
    { suburb_id: 20, town: 'HARARE', suburb: 'BELGRAVIA' },
    { suburb_id: 21, town: 'BULAWAYO', suburb: 'BELLEVUE' },
    { suburb_id: 22, town: 'BULAWAYO', suburb: 'BELMONT' },
    { suburb_id: 23, town: 'HARARE', suburb: 'BELVEDERE' },
    { suburb_id: 24, town: 'KWEKWE', suburb: 'BERVELY HILLS' },
    { suburb_id: 25, town: 'ZVISHAVANE', suburb: 'BIRTHDAY' },
    { suburb_id: 26, town: 'HARARE', suburb: 'BLUFFHILL' },
    { suburb_id: 27, town: 'MARONDERA', suburb: 'BORRADAILE' },
    { suburb_id: 28, town: 'HARARE', suburb: 'BORROWDALE' },
    { suburb_id: 29, town: 'GWERU', suburb: 'BRACKHURST' },
    { suburb_id: 30, town: 'BULAWAYO', suburb: 'BRADFIELD' },
    { suburb_id: 31, town: 'HARARE', suburb: 'BRAESIDE' },
    { suburb_id: 32, town: 'CHINHOYI', suburb: 'BRUINDISH' },
    { suburb_id: 33, town: 'HARARE', suburb: 'BUDIRIRO' },
    { suburb_id: 34, town: 'BULAWAYO', suburb: 'BURNSIDE' },
    { suburb_id: 35, town: 'MASVINGO', suburb: 'BUSHEMEAD' },
    { suburb_id: 36, town: 'KADOMA', suburb: 'CECIL ESTATES' },
    { suburb_id: 37, town: 'BULAWAYO', suburb: 'CHABALALA' },
    { suburb_id: 38, town: 'HARARE', suburb: 'CHADCOMBE' },
    { suburb_id: 39, town: 'MHANGURA', suburb: 'CHEBANGA' },
    { suburb_id: 40, town: 'MARONDERA', suburb: 'CHERUTOMBO' },
    { suburb_id: 41, town: 'MASVINGO', suburb: 'CHESVINGO' },
    { suburb_id: 42, town: 'KWEKWE', suburb: 'CHICAGO' },
    { suburb_id: 43, town: 'MUTARE', suburb: 'CHIKANGA' },
    { suburb_id: 44, town: 'KAROI', suburb: 'CHIKANGWE' },
    { suburb_id: 45, town: 'MASVINGO', suburb: 'CHIKATO' },
    { suburb_id: 46, town: 'CHINHOYI', suburb: 'CHIKONOHONO' },
    { suburb_id: 47, town: 'HARARE', suburb: 'CHIKURUBI' },
    { suburb_id: 48, town: 'MUREWA', suburb: 'CHINONDO' },
    { suburb_id: 49, town: 'VICTORIA FALLS', suburb: 'CHINOTIMBA' },
    { suburb_id: 50, town: 'BINDURA', suburb: 'CHIPADZE' },
    { suburb_id: 51, town: 'CHIPINGE', suburb: 'CHIPINGE' },
    { suburb_id: 52, town: 'HARARE', suburb: 'CHISIPITE' },
    { suburb_id: 53, town: 'CHINHOYI', suburb: 'CHITAMBO' },
    { suburb_id: 54, town: 'MARONDERA', suburb: 'CHITEPO' },
    { suburb_id: 55, town: 'CHINHOYI', suburb: 'CHITOMBORWIZI' },
    { suburb_id: 56, town: 'CHIVHU', suburb: 'CHIVHU TOWNSHIP' },
    { suburb_id: 57, town: 'BINDURA', suburb: 'CHIWARIDZO' },
    { suburb_id: 58, town: 'MVURWI', suburb: 'CHIZHANJE' },
    { suburb_id: 59, town: 'CHINHOYI', suburb: 'COLD STREAM' },
    { suburb_id: 60, town: 'BULAWAYO', suburb: 'COWDRAY PARK' },
    { suburb_id: 61, town: 'HARARE', suburb: 'CRANBOURNE' },
    { suburb_id: 62, town: 'HARARE', suburb: 'CROWBROUGH' },
    { suburb_id: 63, town: 'MHANGURA', suburb: 'DAMBA' },
    { suburb_id: 64, town: 'MUTARE', suburb: 'DANGAMVURA' },
    { suburb_id: 65, town: 'MUTARE', suburb: 'DARLINGTON' },
    { suburb_id: 66, town: 'GWERU', suburb: 'DAYLESFORD' },
    { suburb_id: 67, town: 'MARONDERA', suburb: 'DOMBOTOMBO' },
    { suburb_id: 68, town: 'BULAWAYO', suburb: 'DONNINGTON' },
    { suburb_id: 69, town: 'BULAWAYO', suburb: 'DOUGLASDALE' },
    { suburb_id: 70, town: 'BEIT BRIDGE', suburb: 'DULIBADZIMU' },
    { suburb_id: 71, town: 'HARARE', suburb: 'DZIVARASEKWA' },
    { suburb_id: 72, town: 'MASVINGO', suburb: 'EAST VALE' },
    { suburb_id: 73, town: 'KADOMA', suburb: 'EAST VIEW' },
    { suburb_id: 74, town: 'HARARE', suburb: 'EASTLEA' },
    { suburb_id: 75, town: 'CHIVHU', suburb: 'EASTWOOD' },
    { suburb_id: 76, town: 'KADOMA', suburb: 'EIFFEL FLATS' },
    { suburb_id: 77, town: 'HARARE', suburb: 'EMERALD HILL' },
    { suburb_id: 78, town: 'BULAWAYO', suburb: 'EMGANWINI' },
    { suburb_id: 79, town: 'HWANKE', suburb: 'EMPUMALANGA' },
    { suburb_id: 80, town: 'BULAWAYO', suburb: 'ENTUMBANE' },
    { suburb_id: 81, town: 'HARARE', suburb: 'EPWORTH' },
    { suburb_id: 82, town: 'MUTARE', suburb: 'FAIRBRIDGE PARK' },
    { suburb_id: 83, town: 'BULAWAYO', suburb: 'FAMONA' },
    { suburb_id: 84, town: 'KWEKWE', suburb: 'FITCHLEA' },
    { suburb_id: 85, town: 'KAROI', suburb: 'FLAMBOYANT PARK' },
    { suburb_id: 86, town: 'NORTON', suburb: 'FLAMINGO' },
    { suburb_id: 87, town: 'MUTARE', suburb: 'FLORIDA' },
    { suburb_id: 88, town: 'CHINHOYI', suburb: 'GADZEMA' },
    { suburb_id: 89, town: 'BULAWAYO', suburb: 'GARDEN PARK' },
    { suburb_id: 90, town: 'CHIPINGE', suburb: 'GAZA' },
    { suburb_id: 91, town: 'GWANDA', suburb: 'GENEVA' },
    { suburb_id: 92, town: 'GLEN DALE', suburb: 'GLEN DALE' },
    { suburb_id: 93, town: 'HARARE', suburb: 'GLEN LORNE' },
    { suburb_id: 94, town: 'HARARE', suburb: 'GLEN NORAH' },
    { suburb_id: 95, town: 'HARARE', suburb: 'GLEN VIEW' },
    { suburb_id: 96, town: 'BULAWAYO', suburb: 'GLENCOE' },
    { suburb_id: 97, town: 'BULAWAYO', suburb: 'GLENGARRY' },
    { suburb_id: 98, town: 'GUTU', suburb: 'GONVILLE' },
    { suburb_id: 99, town: 'BINGA', suburb: 'GOVERA' },
    { suburb_id: 100, town: 'HARARE', suburb: 'GRANITESIDE' },
    { suburb_id: 101, town: 'HARARE', suburb: 'GREENCROFT' },
    { suburb_id: 102, town: 'HARARE', suburb: 'GREENDALE' },
    { suburb_id: 103, town: 'BINDURA', suburb: 'GREENHILL' },
    { suburb_id: 104, town: 'MUTARE', suburb: 'GREENSIDE' },
    { suburb_id: 105, town: 'BULAWAYO', suburb: 'GREENVILLE' },
    { suburb_id: 106, town: 'CHEGUTU', suburb: 'GREENWAY' },
    { suburb_id: 107, town: 'HARARE', suburb: 'GREYSTONE PARK' },
    { suburb_id: 108, town: 'HARARE', suburb: 'GROOMBRIDGE' },
    { suburb_id: 109, town: 'CHINHOYI', suburb: 'GUNHILL' },
    { suburb_id: 110, town: 'HARARE', suburb: 'GUNHILL' },
    { suburb_id: 111, town: 'GUTU', suburb: 'GUNVILLE' },
    { suburb_id: 112, town: 'BULAWAYO', suburb: 'GWABALANDA' },
    { suburb_id: 113, town: 'HARARE', suburb: 'HATCLIFFE' },
    { suburb_id: 114, town: 'HARARE', suburb: 'HATFIELD' },
    { suburb_id: 115, town: 'KWEKWE', suburb: 'HAZELDEN' },
    { suburb_id: 116, town: 'HARARE', suburb: 'HELENSVALE' },
    { suburb_id: 117, town: 'CHEGUTU', suburb: 'HEROES' },
    { suburb_id: 118, town: 'BULAWAYO', suburb: 'HIDE PARK' },
    { suburb_id: 119, town: 'BINGA', suburb: 'HIGH DENSITY SURBUBS' },
    { suburb_id: 120, town: 'HARARE', suburb: 'HIGHFIELD' },
    { suburb_id: 121, town: 'HARARE', suburb: 'HIGHLANDS' },
    { suburb_id: 122, town: 'ZVISHAVANE', suburb: 'HIGHLANDS' },
    { suburb_id: 123, town: 'BULAWAYO', suburb: 'HIGHMOUNT' },
    { suburb_id: 124, town: 'BULAWAYO', suburb: 'HILLCREST' },
    { suburb_id: 125, town: 'BULAWAYO', suburb: 'HILLSIDE' },
    { suburb_id: 126, town: 'HARARE', suburb: 'HILLSIDE' },
    { suburb_id: 127, town: 'MASVINGO', suburb: 'HILLSIDE' },
    { suburb_id: 128, town: 'HWANKE', suburb: 'HILLSIDE PARK' },
    { suburb_id: 129, town: 'ZVISHAVANE', suburb: 'HILLVIEW' },
    { suburb_id: 130, town: 'CHEGUTU', suburb: 'HONTONVILLE' },
    { suburb_id: 131, town: 'MUTARE', suburb: 'HOSPITAL HILL' },
    { suburb_id: 132, town: 'HARARE', suburb: 'HOUGHTON PARK' },
    { suburb_id: 133, town: 'CHINHOYI', suburb: 'HUNYANI' },
    { suburb_id: 134, town: 'BULAWAYO', suburb: 'ILANDA' },
    { suburb_id: 135, town: 'HWANKE', suburb: 'INGAGULA' },
    { suburb_id: 136, town: 'KADOMA', suburb: 'INGEZI' },
    { suburb_id: 137, town: 'SHURUGWI', suburb: 'IRONIKOP' },
    { suburb_id: 138, town: 'SHURUGWI', suburb: 'IRONSIDES' },
    { suburb_id: 139, town: 'GWERU', suburb: 'IVENE' },
    { suburb_id: 140, town: 'GWANDA', suburb: 'JACARANDA' },
    { suburb_id: 141, town: 'GWANDA', suburb: 'JAHUNDA' },
    { suburb_id: 142, town: 'HARARE', suburb: 'KAMBANJI' },
    { suburb_id: 143, town: 'HARARE', suburb: 'KAMBUZUMA' },
    { suburb_id: 144, town: 'HARARE', suburb: 'KAMFINSA' },
    { suburb_id: 145, town: 'ZVISHAVANE', suburb: 'KANDODO' },
    { suburb_id: 146, town: 'KARIBA', suburb: 'KARIBA HEIGHTS' },
    { suburb_id: 147, town: 'KAROI', suburb: 'KAROI' },
    { suburb_id: 148, town: 'CHINHOYI', suburb: 'KATANDA' },
    { suburb_id: 149, town: 'NORTON', suburb: 'KATANGA' },
    { suburb_id: 150, town: 'BULAWAYO', suburb: 'KENILWOTH' },
    { suburb_id: 151, town: 'BULAWAYO', suburb: 'KENSINGTON' },
    { suburb_id: 152, town: 'HARARE', suburb: 'KENSINGTON' },
    { suburb_id: 153, town: 'BULAWAYO', suburb: 'KHUMALO' },
    { suburb_id: 154, town: 'BULAWAYO', suburb: 'KILLARNY' },
    { suburb_id: 155, town: 'BULAWAYO', suburb: 'KINGS DALE' },
    { suburb_id: 156, town: 'GWERU', suburb: 'KINGSTON PARK' },
    { suburb_id: 157, town: 'CHINHOYI', suburb: 'KOPJE' },
    { suburb_id: 158, town: 'HARARE', suburb: 'KOPJE' },
    { suburb_id: 159, town: 'BANKET', suburb: 'KUWADZANA' },
    { suburb_id: 160, town: 'HARARE', suburb: 'KUWADZANA' },
    { suburb_id: 161, town: 'MARONDERA', suburb: 'LENDY PARK' },
    { suburb_id: 162, town: 'HARARE', suburb: 'LINCOLN GREEN' },
    { suburb_id: 163, town: 'GWERU', suburb: 'LIS' },
    { suburb_id: 164, town: 'BULAWAYO', suburb: 'LOBENGULA' },
    { suburb_id: 165, town: 'HARARE', suburb: 'LOCHINVAR' },
    { suburb_id: 166, town: 'HARARE', suburb: 'LOGAN PARK' },
    { suburb_id: 167, town: 'KARIBA', suburb: 'LOMAGUNDI' },
    { suburb_id: 168, town: 'MUREWA', suburb: 'LOW DENSITY SURBUBS' },
    { suburb_id: 169, town: 'MUTOKO', suburb: 'LOW DENSITY SURBUBS' },
    { suburb_id: 170, town: 'GWERU', suburb: 'LUNDI PARK' },
    { suburb_id: 171, town: 'HWANKE', suburb: 'LUSUMBAMI' },
    { suburb_id: 172, town: 'BULAWAYO', suburb: 'LUVEVE' },
    { suburb_id: 173, town: 'HWANKE', suburb: 'LUVONDULU' },
    { suburb_id: 174, town: 'HWANKE', suburb: 'LWENDULU' },
    { suburb_id: 175, town: 'HARARE', suburb: 'MABELREIGN' },
    { suburb_id: 176, town: 'RUSAPE', suburb: 'MABVAZUVA' },
    { suburb_id: 177, town: 'HARARE', suburb: 'MABVUKU' },
    { suburb_id: 178, town: 'HWANKE', suburb: 'MADUMABISA' },
    { suburb_id: 179, town: 'RUSAPE', suburb: 'MAGAMBA' },
    { suburb_id: 180, town: 'ZVISHAVANE', suburb: 'MAGLAS' },
    { suburb_id: 181, town: 'KAROI', suburb: 'MAGUNJE' },
    { suburb_id: 182, town: 'BULAWAYO', suburb: 'MAGWEGWE' },
    { suburb_id: 183, town: 'BULAWAYO', suburb: 'MAHATSHULA' },
    { suburb_id: 184, town: 'KARIBA', suburb: 'MAHOMBEKOMBE' },
    { suburb_id: 185, town: 'BULAWAYO', suburb: 'MAKOKOBA' },
    { suburb_id: 186, town: 'CHITUNGWIZA', suburb: 'MAKONI' },
    { suburb_id: 187, town: 'SHURUGWI', suburb: 'MAKUSHA' },
    { suburb_id: 188, town: 'CHIREDZI', suburb: 'MAKUVATSINE' },
    { suburb_id: 189, town: 'ZVISHAVANE', suburb: 'MAKWASHA' },
    { suburb_id: 190, town: 'HARARE', suburb: 'MALBOROUGH' },
    { suburb_id: 191, town: 'BULAWAYO', suburb: 'MALINDELA' },
    { suburb_id: 192, town: 'GWERU', suburb: 'MAMBO' },
    { suburb_id: 193, town: 'HARARE', suburb: 'MANDARA' },
    { suburb_id: 194, town: 'ZVISHAVANE', suburb: 'MANDAVA' },
    { suburb_id: 195, town: 'HARARE', suburb: 'MANYAME' },
    { suburb_id: 196, town: 'GLEN DALE', suburb: 'MASASA' },
    { suburb_id: 197, town: 'HARARE', suburb: 'MASASA' },
    { suburb_id: 198, town: 'ZVISHAVANE', suburb: 'MASHAVI' },
    { suburb_id: 199, town: 'BULAWAYO', suburb: 'MATS' },
    { suburb_id: 200, town: 'BULAWAYO', suburb: 'MATSHEUMHLOPE' },
    { suburb_id: 201, town: 'RUSAPE', suburb: 'MAUNGWE' },
    { suburb_id: 202, town: 'MUREWA', suburb: 'MAVURUME' },
    { suburb_id: 203, town: 'HARARE', suburb: 'MAYFIELD PARK' },
    { suburb_id: 204, town: 'HARARE', suburb: 'MBARE' },
    { suburb_id: 205, town: 'KWEKWE', suburb: 'MBIZO' },
    { suburb_id: 206, town: 'BINGA', suburb: 'MEDIUM DENSITY' },
    { suburb_id: 207, town: 'CHIPINGE', suburb: 'MEDIUM DENSITY' },
    { suburb_id: 208, town: 'MUREWA', suburb: 'MEDIUM DENSITY' },
    { suburb_id: 209, town: 'MUTOKO', suburb: 'MEDIUM DENSITY' },
    { suburb_id: 210, town: 'NORTON', suburb: 'MERTON PARK' },
    { suburb_id: 211, town: 'HARARE', suburb: 'MEYRICK PARK' },
    { suburb_id: 212, town: 'HARARE', suburb: 'MILTON PARK' },
    { suburb_id: 213, town: 'GWERU', suburb: 'MKOBA' },
    { suburb_id: 214, town: 'VICTORIA FALLS', suburb: 'MKOSANA' },
    { suburb_id: 215, town: 'BINGA', suburb: 'MLIBIZI' },
    { suburb_id: 216, town: 'KADOMA', suburb: 'MONINGTON' },
    { suburb_id: 217, town: 'BULAWAYO', suburb: 'MONTROSE' },
    { suburb_id: 218, town: 'BULAWAYO', suburb: 'MORNINGSIDE' },
    { suburb_id: 219, town: 'HARARE', suburb: 'MORNINGSIDE' },
    { suburb_id: 220, town: 'MASVINGO', suburb: 'MORNINGSIDE' },
    { suburb_id: 221, town: 'MUTARE', suburb: 'MORNINGSIDE' },
    { suburb_id: 222, town: 'GUTU', suburb: 'MPANDAWANA' },
    { suburb_id: 223, town: 'CHINHOYI', suburb: 'MPATA' },
    { suburb_id: 224, town: 'BULAWAYO', suburb: 'MPOPOMA' },
    { suburb_id: 225, town: 'HARARE', suburb: 'MSASA PARK' },
    { suburb_id: 226, town: 'KWEKWE', suburb: 'MSASA PARK' },
    { suburb_id: 227, town: 'MASVINGO', suburb: 'MSHAGASHE' },
    { suburb_id: 228, town: 'KADOMA', suburb: 'M SHUMAVALE' },
    { suburb_id: 229, town: 'HARARE', suburb: 'MT PLEASANT' },
    { suburb_id: 230, town: 'CHIPINGE', suburb: 'MT SELINDA' },
    { suburb_id: 231, town: 'MASVINGO', suburb: 'MUCHEKE' },
    { suburb_id: 232, town: 'HARARE', suburb: 'MUFAKOSE' },
    { suburb_id: 233, town: 'TRIANGLE', suburb: 'MUFAKOSE' },
    { suburb_id: 234, town: 'MUREWA', suburb: 'MUJURU' },
    { suburb_id: 235, town: 'MUREWA', suburb: 'MUKURAZHIZHA' },
    { suburb_id: 236, town: 'MUTARE', suburb: 'MURAMBI' },
    { suburb_id: 237, town: 'SELOUS', suburb: 'MUROMBEDZI' },
    { suburb_id: 238, town: 'MVUMA', suburb: 'MUSHANDIRAPAMWE' },
    { suburb_id: 239, town: 'MVUMA', suburb: 'MUSHAYAVHUDZI' },
    { suburb_id: 240, town: 'CHINHOYI', suburb: 'MUZARI' },
    { suburb_id: 241, town: 'BULAWAYO', suburb: 'MZILIKAZI' },
    { suburb_id: 242, town: 'BINDURA', suburb: 'NANDE VILLAS' },
    { suburb_id: 243, town: 'GWERU', suburb: 'NASHVILLE' },
    { suburb_id: 244, town: 'GWERU', suburb: 'NEHOSHO' },
    { suburb_id: 245, town: 'CHIVHU', suburb: 'NEW STANDS' },
    { suburb_id: 246, town: 'CHIPINGE', suburb: 'NEWCASTLE' },
    { suburb_id: 247, town: 'HARARE', suburb: 'NEWLANDS' },
    { suburb_id: 248, town: 'BULAWAYO', suburb: 'NEWTON WEST' },
    { suburb_id: 249, town: 'KWEKWE', suburb: 'NEWTOWN' },
    { suburb_id: 250, town: 'NORTON', suburb: 'NGONI' },
    { suburb_id: 251, town: 'HWANKE', suburb: 'NGUMIJA' },
    { suburb_id: 252, town: 'SHURUGWI', suburb: 'NHARIRA' },
    { suburb_id: 253, town: 'NORTON', suburb: 'NHARIRA VIEW' },
    { suburb_id: 254, town: 'BULAWAYO', suburb: 'NJUBE' },
    { suburb_id: 255, town: 'BULAWAYO', suburb: 'NKETA' },
    { suburb_id: 256, town: 'BULAWAYO', suburb: 'NKULUMANE' },
    { suburb_id: 257, town: 'ZVISHAVANE', suburb: 'NOELVALE' },
    { suburb_id: 258, town: 'KAROI', suburb: 'NORTH INFILL' },
    { suburb_id: 259, town: 'HWANKE', suburb: 'NORTH SHAFT' },
    { suburb_id: 260, town: 'BULAWAYO', suburb: 'NORTHEND' },
    { suburb_id: 261, town: 'BULAWAYO', suburb: 'NORTHLEA' },
    { suburb_id: 262, town: 'GWERU', suburb: 'NORTHLEA' },
    { suburb_id: 263, town: 'KWEKWE', suburb: 'NORTHLEIGH' },
    { suburb_id: 264, town: 'MASVINGO', suburb: 'NORTHLEIGH' },
    { suburb_id: 265, town: 'BULAWAYO', suburb: 'NORTHVALE' },
    { suburb_id: 266, town: 'HARARE', suburb: 'NORTHWOOD' },
    { suburb_id: 267, town: 'MARONDERA', suburb: 'NYAMENI' },
    { suburb_id: 268, town: 'NYANGA', suburb: 'NYAMHUKA' },
    { suburb_id: 269, town: 'KARIBA', suburb: 'NYAMHUNGA' },
    { suburb_id: 270, town: 'CHINHOYI', suburb: 'ORANGE GROOVE' },
    { suburb_id: 271, town: 'BULAWAYO', suburb: 'PADDONHURST' },
    { suburb_id: 272, town: 'MUTARE', suburb: 'PALMERSTONE' },
    { suburb_id: 273, town: 'MARONDERA', suburb: 'PARADISE' },
    { suburb_id: 274, town: 'BULAWAYO', suburb: 'PARKLANDS' },
    { suburb_id: 275, town: 'MARONDERA', suburb: 'PARKLANDS' },
    { suburb_id: 276, town: 'HARARE', suburb: 'PARKTOWN' },
    { suburb_id: 277, town: 'MUTARE', suburb: 'PAULINGTON' },
    { suburb_id: 278, town: 'BULAWAYO', suburb: 'PELANDABA' },
    { suburb_id: 279, town: 'CHEGUTU', suburb: 'PFUPAJENA' },
    { suburb_id: 280, town: 'GWANDA', suburb: 'PHAKAMA' },
    { suburb_id: 281, town: 'GWANDA', suburb: 'PHELENDABA' },
    { suburb_id: 282, town: 'BULAWAYO', suburb: 'PHUMULA' },
    { suburb_id: 283, town: 'ZVISHAVANE', suburb: 'PLATINUM PARK' },
    { suburb_id: 284, town: 'HARARE', suburb: 'PROSPECT' },
    { suburb_id: 285, town: 'BULAWAYO', suburb: 'QUEENS PARK' },
    { suburb_id: 286, town: 'HARARE', suburb: 'QUEENSDALE' },
    { suburb_id: 287, town: 'CHIREDZI', suburb: 'RAILWAY SURBUBS' },
    { suburb_id: 288, town: 'BULAWAYO', suburb: 'RANGEMORE' },
    { suburb_id: 289, town: 'HWANKE', suburb: 'RAYLTON' },
    { suburb_id: 290, town: 'RUSAPE', suburb: 'REST HAVEN' },
    { suburb_id: 291, town: 'MASVINGO', suburb: 'RHODENE' },
    { suburb_id: 292, town: 'HARARE', suburb: 'RHODESVILLE' },
    { suburb_id: 293, town: 'BULAWAYO', suburb: 'RICHMOND' },
    { suburb_id: 294, town: 'GWERU', suburb: 'RIDGEMONT' },
    { suburb_id: 295, town: 'HARARE', suburb: 'RIDGEVIEW' },
    { suburb_id: 296, town: 'CHEGUTU', suburb: 'RIFLE RANGE' },
    { suburb_id: 297, town: 'MUREWA', suburb: 'RIMBI' },
    { suburb_id: 298, town: 'KADOMA', suburb: 'RIMUKA' },
    { suburb_id: 299, town: 'BULAWAYO', suburb: 'RIVERSIDE' },
    { suburb_id: 300, town: 'GWERU', suburb: 'RIVERSIDE' },
    { suburb_id: 301, town: 'MASVINGO', suburb: 'RIVERSIDE' },
    { suburb_id: 302, town: 'BULAWAYO', suburb: 'ROMNEY PARK' },
    { suburb_id: 303, town: 'TRIANGLE', suburb: 'RUFARO' },
    { suburb_id: 304, town: 'RUSAPE', suburb: 'RUGARE' },
    { suburb_id: 305, town: 'GLEN DALE', suburb: 'RUJEKO' },
    { suburb_id: 306, town: 'MARONDERA', suburb: 'RUJEKO' },
    { suburb_id: 307, town: 'MASVINGO', suburb: 'RUJEKO' },
    { suburb_id: 308, town: 'MASVINGO', suburb: 'RUNYARARO' },
    { suburb_id: 309, town: 'MARONDERA', suburb: 'RUSIKE PARK' },
    { suburb_id: 310, town: 'MVURWI', suburb: 'RUSUNUNGUKO' },
    { suburb_id: 311, town: 'MARONDERA', suburb: 'RUVIMBO PARK' },
    { suburb_id: 312, town: 'MARONDERA', suburb: 'RUWARE PARK' },
    { suburb_id: 313, town: 'MARONDERA', suburb: 'RUZAWI PARK' },
    { suburb_id: 314, town: 'MUREWA', suburb: 'RUZE' },
    { suburb_id: 315, town: 'RUSAPE', suburb: 'SABLE RANGE' },
    { suburb_id: 316, town: 'GWANDA', suburb: 'SABLEVALE' },
    { suburb_id: 317, town: 'MUTARE', suburb: 'SAKUBVA' },
    { suburb_id: 318, town: 'BULAWAYO', suburb: 'SAUERSTOWN' },
    { suburb_id: 319, town: 'SHURUGWI', suburb: 'SEBANGA' },
    { suburb_id: 320, town: 'CHITUNGWIZA', suburb: 'SEKE' },
    { suburb_id: 321, town: 'BULAWAYO', suburb: 'SELBONE PARK' },
    { suburb_id: 322, town: 'GWERU', suburb: 'SENKA' },
    { suburb_id: 323, town: 'GWANDA', suburb: 'SENONDO' },
    { suburb_id: 324, town: 'HARARE', suburb: 'SENTOSA' },
    { suburb_id: 325, town: 'BINDURA', suburb: 'SHASHI VIEW' },
    { suburb_id: 326, town: 'KWEKWE', suburb: 'SHERWOOD' },
    { suburb_id: 327, town: 'MUREWA', suburb: 'SISK LOCATION' },
    { suburb_id: 328, town: 'BULAWAYO', suburb: 'SIZINDA' },
    { suburb_id: 329, town: 'MARONDERA', suburb: 'SOUTH ASHLINGS' },
    { suburb_id: 330, town: 'HWANKE', suburb: 'SOUTH CLIFF' },
    { suburb_id: 331, town: 'KWEKWE', suburb: 'SOUTH WOOD' },
    { suburb_id: 332, town: 'BULAWAYO', suburb: 'SOUTH WORLD' },
    { suburb_id: 333, town: 'GWERU', suburb: 'SOUTHDOWNS' },
    { suburb_id: 334, town: 'HARARE', suburb: 'SOUTHERTON' },
    { suburb_id: 335, town: 'GWERU', suburb: 'SOUTHVIEW' },
    { suburb_id: 336, town: 'GWANDA', suburb: 'SPITZKOP' },
    { suburb_id: 337, town: 'CHITUNGWIZA', suburb: 'ST MARYS' },
    { suburb_id: 338, town: 'HARARE', suburb: 'STRATHHAVEN' },
    { suburb_id: 339, town: 'BULAWAYO', suburb: 'SUNNING HILL' },
    { suburb_id: 340, town: 'HARARE', suburb: 'SUNNINGDALE' },
    { suburb_id: 341, town: 'BULAWAYO', suburb: 'SUNNY SIDE' },
    { suburb_id: 342, town: 'MVURWI', suburb: 'SUOGURU' },
    { suburb_id: 343, town: 'BULAWAYO', suburb: 'SURBUBS' },
    { suburb_id: 344, town: 'HARARE', suburb: 'TAFARA' },
    { suburb_id: 345, town: 'BULAWAYO', suburb: 'TEGELA' },
    { suburb_id: 346, town: 'KAROI', suburb: 'TENGWE' },
    { suburb_id: 347, town: 'CHIVHU', suburb: 'TERRABLANCHEST' },
    { suburb_id: 348, town: 'BULAWAYO', suburb: 'THORN GROOVE' },
    { suburb_id: 349, town: 'GWERU', suburb: 'THORNHILL' },
    { suburb_id: 350, town: 'MUTARE', suburb: 'TIGER KLOOF' },
    { suburb_id: 351, town: 'RUSAPE', suburb: 'TSANZAGURU' },
    { suburb_id: 352, town: 'CHIREDZI', suburb: 'TSHOVANI' },
    { suburb_id: 353, town: 'GLEN DALE', suburb: 'TSUNGUBVI' },
    { suburb_id: 354, town: 'NORTON', suburb: 'TWINLAKES' },
    { suburb_id: 355, town: 'HARARE', suburb: 'TYNWALD' },
    { suburb_id: 356, town: 'CHEGUTU', suburb: 'UMVOVO' },
    { suburb_id: 357, town: 'HARARE', suburb: 'UMWINSDALE' },
    { suburb_id: 358, town: 'HARARE', suburb: 'VAINONA' },
    { suburb_id: 359, town: 'RUSAPE', suburb: 'VENGERE' },
    { suburb_id: 360, town: 'SHAMVA', suburb: 'WADZANAYI' },
    { suburb_id: 361, town: 'HWANKE', suburb: 'WANKIE COLLIERY' },
    { suburb_id: 362, town: 'HARARE', suburb: 'WARREN PARK' },
    { suburb_id: 363, town: 'HARARE', suburb: 'WATER FALLS' },
    { suburb_id: 364, town: 'BULAWAYO', suburb: 'WATER FORD' },
    { suburb_id: 365, town: 'KADOMA', suburb: 'WAVERLY' },
    { suburb_id: 366, town: 'KADOMA', suburb: 'WEST VIEW' },
    { suburb_id: 367, town: 'HARARE', suburb: 'WESTGATE' },
    { suburb_id: 368, town: 'MUTARE', suburb: 'WESTLEA' },
    { suburb_id: 369, town: 'GLEN DALE', suburb: 'WESTVILLE PARK' },
    { suburb_id: 370, town: 'CHIVHU', suburb: 'WESTWOOD' },
    { suburb_id: 371, town: 'HARARE', suburb: 'WESTWOOD' },
    { suburb_id: 372, town: 'CHINHOYI', suburb: 'WHITE CITY' },
    { suburb_id: 373, town: 'BULAWAYO', suburb: 'WILLSGROVE' },
    { suburb_id: 374, town: 'BANKET', suburb: 'WILMAR PARK' },
    { suburb_id: 375, town: 'HARARE', suburb: 'WILMINGTON PARK' },
    { suburb_id: 376, town: 'BULAWAYO', suburb: 'WOODVILLE PARK' },
    { suburb_id: 377, town: 'HARARE', suburb: 'WORKINGTON' },
    { suburb_id: 378, town: 'NORTON', suburb: 'WORKINGTON' },
    { suburb_id: 379, town: 'BULAWAYO', suburb: 'WORRINGHAM' },
    { suburb_id: 380, town: 'MARONDERA', suburb: 'YELLOW CITY' },
    { suburb_id: 381, town: 'MUTARE', suburb: 'YEOVIL' },
    { suburb_id: 382, town: 'CHITUNGWIZA', suburb: 'ZENGEZA' },
    { suburb_id: 383, town: 'HARARE', suburb: 'ZIMRE PARK' },
    { suburb_id: 384, town: 'TRIANGLE', suburb: 'ZORORO' }
  ];

  const batchSize = 50;
  for (let i = 0; i < suburbsTowns.length; i += batchSize) {
    const batch = suburbsTowns.slice(i, i + batchSize);
    await knex('enum_suburbs_towns').insert(batch);
  }

  console.log('✓ Suburbs and towns seeded successfully (384 entries)');
};
